<?php
/**
 * ConfigurationOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Formitable Api v1.2
 *
 * New in this version: <ul><li>Added Get Single restaurant operation.</li><li>Verify availability for a datetime / partysize.</li><li>Select tables with create and update booking.</li><li>Get tables and areas by the POS identifiers</li></ul>
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConfigurationOptionTest Class Doc Comment
 *
 * @category    Class
 * @description Contains information about a bookable option. When SpotsOpen &#x3D; 0, this option is full.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationOptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConfigurationOption"
     */
    public function testConfigurationOption()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "party_size"
     */
    public function testPropertyPartySize()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "product_uid"
     */
    public function testPropertyProductUid()
    {
    }

    /**
     * Test attribute "area_id"
     */
    public function testPropertyAreaId()
    {
    }

    /**
     * Test attribute "spots_open"
     */
    public function testPropertySpotsOpen()
    {
    }

    /**
     * Test attribute "spots_total"
     */
    public function testPropertySpotsTotal()
    {
    }

    /**
     * Test attribute "is_squeeze"
     */
    public function testPropertyIsSqueeze()
    {
    }

    /**
     * Test attribute "show_end_time"
     */
    public function testPropertyShowEndTime()
    {
    }

    /**
     * Test attribute "booking_window_min"
     */
    public function testPropertyBookingWindowMin()
    {
    }

    /**
     * Test attribute "booking_window_max"
     */
    public function testPropertyBookingWindowMax()
    {
    }
}
